"""fix schema

Revision ID: cd7a80d72883
Revises: dbf8bfb9cbdd
Create Date: 2026-01-04 14:51:29.557697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd7a80d72883'
down_revision: Union[str, Sequence[str], None] = 'dbf8bfb9cbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('session_id', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('session_id_expires_at', sa.DateTime(), nullable=False))
    op.drop_column('jobs', 'job_token_expires_at')
    op.drop_column('jobs', 'job_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_token_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('job_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'session_id_expires_at')
    op.drop_column('jobs', 'session_id')
    # ### end Alembic commands ###
